### ISSUE TITLE
Can't brew install

### ISSUE THREAD

**Issue by nservidio** [rainforestapp/homebrew-public#8]
Hello,

I'm getting the following issue:
```
brew install rainforestapp/public/rainforest-cli
==> Tapping rainforestapp/public
Cloning into '/usr/local/Homebrew/Library/Taps/rainforestapp/homebrew-public'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 52 (delta 5), reused 6 (delta 2), pack-reused 36
Unpacking objects: 100% (52/52), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rainforestapp/homebrew-public/get_equinox_url.rb
get_equinox_url: cannot load such file -- nokogiri
Error: Cannot tap rainforestapp/public: invalid syntax in tap!
```

I believe you can fix this by changing the organization of your directory:
> Tap formulae follow the same format as the core’s ones, and can be added under either the Formula subdirectory, the HomebrewFormula subdirectory or the repository’s root. The first available directory is used, other locations will be ignored. We recommend use of subdirectories because it makes the repository organisation easier to grasp, and top-level files are not mixed with formulae.

https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by jbarber** [comment]
Thanks for reporting this problem @nservidio.

**Comment by jaytennier** [comment]
Okay @nservidio this should be fixed now:

```
% brew install rainforestapp/public/rainforest-cli
==> Installing rainforest-cli from rainforestapp/public
==> Downloading https://bin.equinox.io/a/7tL4xLZeJqg/rainforest-cli-2.18.2-darwin-amd64.tar.gz
######################################################################## 100.0%
🍺  /usr/local/Cellar/rainforest-cli/64: 3 files, 10.5MB, built in 2 seconds
```

Thanks for letting us know about it!
